manual_tagging/urls.py
from django.conf.urls import url

from . import views

app_name = 'manual_tagging'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^next_tweets/(?P<size>[0-9]+)/$', views.next_tweets, name='next_tweets'),
    url(r'^load_tweet/(?P<tag_id>[0-9]+)/$', views.load_single_tag, name='load_single_tag'),
    url(r'^save_single/$', views.save_single_tag, name='save_single'),
    url(r'^save_tags/$', views.save_tags, name='save_tags'),
    url(r'^latest_classified/$', views.latest_classified, name='latest_classified'),
]

tweets_tagging/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.views.generic.base import RedirectView
from settings import SUB_SITE

urlpatterns = [
    url(r'^$', RedirectView.as_view(url='%s/manual_tagging/' % SUB_SITE, permanent=False), name='home'),
    url(r'^login/$', auth_views.login, {'template_name': 'login.html'}, name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': '%s/login/' % SUB_SITE}, name='logout'),
    url(r'^manual_tagging/', include('manual_tagging.urls')),
    url(r'^admin/', admin.site.urls)
]

manual_tagging/models.py
from __future__ import unicode_literals

from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.contrib.auth.models import User

# Create your models here.


@python_2_unicode_compatible
class TweetDataset(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name


@python_2_unicode_compatible
class TweetClassification(models.Model):
    key = models.CharField(max_length=200, unique=True)
    label = models.CharField(max_length=200)

    def __str__(self):
        return self.label


@python_2_unicode_compatible
class Tweet(models.Model):
    id_from_twitter = models.CharField(max_length=200)
    text = models.TextField()
    previous_classification = models.ForeignKey(TweetClassification, on_delete=models.CASCADE)
    dataset = models.ForeignKey(TweetDataset, on_delete=models.CASCADE)

    def __str__(self):
        return self.text


@python_2_unicode_compatible
class TweetTag(models.Model):
    tweet = models.ForeignKey(Tweet, on_delete=models.CASCADE, editable=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE, editable=False)
    classification = models.ForeignKey(TweetClassification, on_delete=models.CASCADE, null=True)
    last_update = models.DateTimeField(null=True, editable=False)

    def __str__(self):
        if self.classification is not None:
            return "%s classified %s as %s" % (self.user.username, self.tweet.text, self.classification.label)
        else:
            return "%s need to classify %s" % (self.user.username, self.tweet.text)

manual_tagging/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views import generic
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.template.defaulttags import register
from django.db.models import F
from django.db.models import Q
import datetime
from .models import *
# Create your views here.


@login_required
def index(request):
    user = request.user
    total_tweets = TweetTag.objects.filter(user__id=user.id).count()
    total_classified = TweetTag.objects.filter(user__id=user.id, classification__isnull=False).count()
    total_relevant = TweetTag.objects.filter(user__id=user.id, classification__key='RELEVANT').count()
    total_news = TweetTag.objects.filter(user__id=user.id, classification__key='NEWS').count()
    total_noise = TweetTag.objects.filter(user__id=user.id, classification__key='NOISE').count()
    progress = "0%"
    if int(total_tweets) > 0:
        progress = "%.1f%%" % (100*float(total_classified)/total_tweets)
    context = {
        'total_tweets':total_tweets,
        'total_relevant': total_relevant,
        'total_classified': total_classified,
        'total_news': total_news,
        'total_noise': total_noise,
        'progress': progress
    }

    if user.is_superuser:
        all_users_progress = []
        users = User.objects.all().order_by("username")
        for user in users:
            total_tweets = TweetTag.objects.filter(user__id=user.id).count()
            if int(total_tweets) == 0:
                continue
            total_classified = TweetTag.objects.filter(user__id=user.id, classification__isnull=False).count()
            matches = TweetTag.objects.filter(user__id=user.id,
                                              classification__id=F('tweet__previous_classification__id'),
                                              classification__isnull=False).count()
            conflicts = TweetTag.objects.filter(~Q(classification__id=F('tweet__previous_classification__id')),
                                                user__id=user.id,classification__isnull=False).count()
            progress = "%.1f%%" % (100 * float(total_classified) / total_tweets)
            name = user.first_name + " " + user.last_name
            all_users_progress.append((name, total_tweets, total_classified, progress, matches, conflicts))
        context["all_users_progress"] = all_users_progress

    return render(request, 'manual_tagging/index.html', context=context)


@login_required
def save_tags(request):
    for name in request.POST.keys():
        if "classification_tag_" in name:
            tag_id = int(name.split("_")[-1])
            tag = get_object_or_404(TweetTag, pk=tag_id)
            if tag.user.id != request.user.id:
                return HttpResponseRedirect(reverse('manual_tagging:index'))
            classification = get_object_or_404(TweetClassification, pk=int(request.POST[name]))
            tag.classification = classification
            tag.last_update = datetime.datetime.now()
            tag.save()
    return HttpResponseRedirect(reverse('manual_tagging:next_tweets', kwargs={'size': request.POST['size']}))


@login_required
def next_tweets(request, size):
    size = int(size)
    size = max(10, min(size, 100))  # size will be always between 10 and 100 (inclusive)
    empty_tags = TweetTag.objects.filter(user__id=request.user.id, classification=None, last_update=None)[:size]
    classifications = TweetClassification.objects.all().order_by('label')
    context = {'tags': empty_tags, 'classifications': classifications, 'size': size}
    return render(request, 'manual_tagging/next_tweets.html', context)


@login_required
def latest_classified(request):
    user_id = request.user.id
    last = TweetTag.objects.filter(user__id=user_id, classification__isnull=False).order_by("-last_update")[:100]
    context = {'last': last}
    return render(request, 'manual_tagging/latest_classified.html', context)


@login_required
def save_single_tag(request):
    for name in request.POST.keys():
        if "classification_tag_" in name:
            tag_id = int(name.split("_")[-1])
            tag = get_object_or_404(TweetTag, pk=tag_id)
            if tag.user.id != request.user.id:
                return HttpResponseRedirect(reverse('manual_tagging:index'))
            classification = get_object_or_404(TweetClassification, pk=int(request.POST[name]))
            tag.classification = classification
            tag.last_update = datetime.datetime.now()
            tag.save()
    return HttpResponseRedirect(reverse('manual_tagging:latest_classified'))


@login_required
def load_single_tag(request, tag_id):
    tag = get_object_or_404(TweetTag, pk=tag_id)
    classifications = TweetClassification.objects.all().order_by('label')
    context = {'tag': tag, 'classifications': classifications}
    return render(request, 'manual_tagging/single_tweet.html', context)

manual_tagging/templates/manual_tagging/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    {% if total_tweets > 0 %}
        <div class="page-header">
            <h1>Your Progress</h1>
        </div>
        <table class="table table-hover">
            <thead>
            <tr>
                <th>Description</th>
                <th>Value</th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td>Total Number of Tweets</td>
                <td>{{ total_tweets }}</td>
            </tr>
            <tr>
                <td>Classified Tweets</td>
                <td>{{ total_classified }} ({{ progress }})</td>
            </tr>
            <tr>
                <td>Tweets Classified as Relevant</td>
                <td>{{ total_relevant }}</td>
            </tr>
            <tr>
                <td>Tweets Classified as News</td>
                <td>{{ total_news }}</td>
            </tr>
            <tr>
                <td>Tweets Classified as Noise</td>
                <td>{{ total_noise }}</td>
            </tr>
            </tbody>
        </table>
    {% endif %}
    {% if request.user.is_superuser %}
        <div class="page-header">
            <h1>Task Overview</h1>
        </div>
        <table class="table table-hover">
            <thead>
            <tr>
                <th>User</th>
                <th>Total Number of Tweets</th>
                <th>Classified Tweets</th>
                <th>Progress</th>
                <th>Matches</th>
                <th>Conflicts</th>
            </tr>
            </thead>
            <tbody>
            {% for stats in all_users_progress %}
                <tr>
                    <td>{{ stats.0 }}</td>
                    <td>{{ stats.1 }}</td>
                    <td>{{ stats.2 }}</td>
                    <td>{{ stats.3 }}</td>
                    <td>{{ stats.4 }}</td>
                    <td>{{ stats.5 }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    {% endif %}
{% endblock %}

manual_tagging/templates/manual_tagging/latest_classified.html
{% extends 'base.html' %}
{% load static %}

{% block header %}
    <script src="{% static 'manual_tagging/js/next_tweets.js' %}"></script>
{% endblock %}

{% block content %}
    <div class="page-header">
        <h1>Latest Classified</h1>
    </div>

    {% if last %}
        <table class="table table-hover">
            <thead>
            <tr>
                <th>#</th>
                <th>Tweet</th>
                <th>Classification</th>
                <th width="200px;">Date and Time</th>
            </tr>
            </thead>
            <tbody>
            {% for tag in last %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>
                        <a title="Change classification" href="{% url 'manual_tagging:load_single_tag' tag.id %}">
                            {{ tag.tweet.text }}
                        </a>
                    </td>
                    <td>{{ tag.classification.label }}</td>
                    <td>{{ tag.last_update }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    {% else %}
        <p>You have not classified any tweets yet :(</p>
    {% endif %}

{% endblock %}

manual_tagging/templates/manual_tagging/next_tweets.html
{% extends 'base.html' %}
{% load static %}

{% block header %}
    <script src="{% static 'manual_tagging/js/next_tweets.js' %}"></script>
{% endblock %}

{% block content %}
    <div class="container">
    <div class="page-header">
        <div class="row">
            <div class="col-md-6"><h1>Tweets to Classify <small>showing {{ tags|length }} tweets</small></h1></div>
            <div style="padding-top: 22px;" class="col-md-6 align-middle">
                <div class="btn-group pull-right" role="group">
                    <a href="{% url 'manual_tagging:next_tweets' 10 %}"
                       role="button"
                       class="btn btn-default {% if '/10/' in request.path %} active {% endif %}">
                        10
                    </a>
                    <a href="{% url 'manual_tagging:next_tweets' 25 %}"
                       role="button"
                       class="btn btn-default {% if '/25/' in request.path %} active {% endif %}">
                        25
                    </a>
                    <a href="{% url 'manual_tagging:next_tweets' 50 %}"
                       role="button"
                       class="btn btn-default {% if '/50/' in request.path %} active {% endif %}">
                        50
                    </a>
                    <a href="{% url 'manual_tagging:next_tweets' 75 %}"
                       role="button"
                       class="btn btn-default {% if '/75/' in request.path %} active {% endif %}">
                        75
                    </a>
                    <a href="{% url 'manual_tagging:next_tweets' 100 %}"
                       role="button"
                       class="btn btn-default {% if '/100/' in request.path %} active {% endif %}">
                        100
                    </a>
                </div>
            </div>
        </div>
    </div>
    </div>

    {% if tags %}
        <form class="form-horizontal" id="form_tags" method="post" action="{% url 'manual_tagging:save_tags' %}">
            <input type="hidden" name="size" value="{{ size }}"/>
            {% csrf_token %}
            {% for tag in tags %}
                <dl class="dl-horizontal">
                    <dt>Tweet</dt>
                    <dd>{{ tag.tweet.text }}</dd>
                    <dt>Classification</dt>
                    <dd>
                        {% for class in classifications %}
                            <label class="radio-inline">
                                <input type="radio" name="classification_tag_{{ tag.id }}"
                                       data-parsley-ui-enabled="false"
                                       value="{{ class.id }}" required/> {{ class.label }}
                            </label>
                        {% endfor %}
                    </dd>
                </dl>
                <hr/>
            {% endfor %}
            <button type="submit" class="btn pull-right btn btn-success btn-lg">Save</button>
        </form>
    {% else %}
        <p>You have finished the manual classification \o/</p>
    {% endif %}
{% endblock %}

manual_tagging/templates/manual_tagging/single_tweet.html
{% extends 'base.html' %}
{% load static %}

{% block header %}
    <script src="{% static 'manual_tagging/js/next_tweets.js' %}"></script>
{% endblock %}

{% block content %}
    <div class="page-header">
        <h1>Change Tweet Classification</h1>
    </div>

    <form class="form-horizontal" id="form_tags" method="post" action="{% url 'manual_tagging:save_single' %}">
        {% csrf_token %}
        <dl class="dl-horizontal">
            <dt>Tweet</dt>
            <dd>{{ tag.tweet.text }}</dd>
            <dt>Classification</dt>
            <dd>
                {% for class in classifications %}
                    <label class="radio-inline">
                        <input type="radio" name="classification_tag_{{ tag.id }}"
                               data-parsley-ui-enabled="false"
                               {% if class.id == tag.classification.id %} checked {% endif %}
                               value="{{ class.id }}" required/> {{ class.label }}
                    </label>
                {% endfor %}
            </dd>
        </dl>
        <button type="submit" class="btn pull-right btn btn-success btn-lg">Save</button>
    </form>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{% block title %}Manual Tagging{% endblock %}</title>

    <style>
        body {
            padding-top: 50px;
        }
    </style>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}"/>

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/ie10-viewport-bug-workaround.css' %}"/>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>

    <script src="{% static 'js/parsley/parsley.min.js' %}"></script>

    {% block header %}
    {% endblock %}
</head>
<body>
<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                    aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'manual_tagging:index'%}">Tweets</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                {% url 'manual_tagging:index' as index_url%}
                <li {% if request.get_full_path == index_url %}class="active"{% endif %}>
                    <a href="{% url 'manual_tagging:index'%}">Task Overview</a>
                </li>
                {% if size %}
                    {% url 'manual_tagging:next_tweets' size as next_tweets_url%}
                {% else %}
                    {% url 'manual_tagging:next_tweets' 10 as next_tweets_url%}
                {% endif %}
                <li {% if request.get_full_path == next_tweets_url %}class="active"{% endif %}>
                    <a href="{% url 'manual_tagging:next_tweets' 10 %}">Classify</a>
                </li>
                {% url 'manual_tagging:latest_classified' as latest_url%}
                <li {% if request.get_full_path == latest_url %}class="active"{% endif %}>
                    <a href="{% url 'manual_tagging:latest_classified' %}">Latest Classified</a>
                </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li><a href="{% url 'logout' %}">Logout</a></li>
            </ul>
        </div><!--/.nav-collapse -->
    </div>
</nav>

<div class="container">

    {% block content %}
    {% endblock %}

</div><!-- /.container -->


<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->


<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/ie10-viewport-bug-workaround.js' %}"></script>
</body>
</html>

templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Experimento - Login</title>

    <!-- Bootstrap core CSS -->

    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}"/>

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/ie10-viewport-bug-workaround.css' %}"/>

    <!-- Custom styles for this template -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/signin.css' %}"/>


    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

<body>


<div class="container">

    <form class="form-signin" method="POST">
        {% csrf_token %}
        <h2 class="form-signin-heading">Tweets</h2>
        <label for="id_username" class="sr-only">Username</label>
        <input type="text" id="id_username" name="username" class="form-control" placeholder="Username" required autofocus>
        <label for="id_password" class="sr-only">Password</label>
        <input type="password" name="password" id="id_password" class="form-control" placeholder="Password" required>
        <button class="btn btn-lg btn-primary btn-block" type="submit">Login</button>
    </form>

</div> <!-- /container -->


<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
<script src="{% static 'js/ie10-viewport-bug-workaround.js' %}"></script>
</body>
</html>